USE Messenger
GO

--================================================================================================
--	Author:		Samkelo Nhlapo
--	Create date	02/08/2021
--	Description	Inserting Genders Table
--	TFS Task	Insert Data
--================================================================================================

INSERT INTO Profile.Genders(GenderName,UpDatedate)
VALUES	('Male',GETDATE()),
		('Female',GETDATE()),
		('Agender',GETDATE()),
		('Androgyne',GETDATE()),
		('Androgynous',GETDATE()),
		('Bigender',GETDATE()),
		('Cis',GETDATE()),
		('Cisgender',GETDATE()),
		('Cis Female',GETDATE()),
		('Cis Male',GETDATE()),
		('Cis Man',GETDATE()),
		('Cis Woman',GETDATE()),
		('Cisgender Female',GETDATE()),
		('Cisgender Male',GETDATE()),
		('Cisgender Man',GETDATE()),
		('Cisgender Woman',GETDATE()),
		('Female to Male',GETDATE()),
		('FTM',GETDATE()),
		('Gender Fluid',GETDATE()),
		('Gender Nonconforming',GETDATE()),
		('Gender Questioning',GETDATE()),
		('Gender Variant',GETDATE()),
		('Genderqueer',GETDATE()),
		('Intersex',GETDATE()),
		('Male to Female',GETDATE()),
		('MTF',GETDATE()),
		('Neither',GETDATE()),
		('Neutrois',GETDATE()),
		('Non-binary',GETDATE()),
		('Other',GETDATE()),
		('Pangender',GETDATE()),
		('Trans',GETDATE()),
		('Trans*',GETDATE()),
		('Trans Female',GETDATE()),
		('Trans* Female',GETDATE()),
		('Trans Male',GETDATE()),
		('Trans* Male',GETDATE()),
		('Trans Man',GETDATE()),
		('Trans* Man',GETDATE()),
		('Trans Person',GETDATE()),
		('Trans* Person',GETDATE()),
		('Trans Woman',GETDATE()),
		('Trans* Woman',GETDATE()),
		('Transfeminine',GETDATE()),
		('Transgender',GETDATE()),
		('Transgender Female',GETDATE()),
		('Transgender Male',GETDATE()),
		('Transgender Man',GETDATE()),
		('Transgender Person',GETDATE()),
		('Transgender Woman',GETDATE()),
		('Transmasculine',GETDATE()),
		('Transsexual',GETDATE()),
		('Transsexual Female',GETDATE()),
		('Transsexual Male',GETDATE()),
		('Transsexual Man',GETDATE()),
		('Transsexual Person',GETDATE()),
		('Transsexual Woman',GETDATE()),
		('Two-Spirit',GETDATE())